import Head from 'next/head'

export default function Layout(props) {
  return (
    <div>
      <Head>
        <title>{props.title}</title>
        <meta name="description"
          content="Generated by create next app" />
      </Head>
      {props.children}
    </div>
  )
}